# -*- coding: utf-8 -*-
"""vehicle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pRJ7u-Y6Dlvy5RiutJbQeKMK-rglVkVx
"""





from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
!mkdir /content/drive/MyDrive/FYP
# %cd /content/drive/MyDrive/FYP
!mkdir YOLOV8_M1

# Commented out IPython magic to ensure Python compatibility.
# %cd YOLOV8_M1

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/FYP/YOLOV8_M1

import os
HOME = os.getcwd()
print(HOME)

# Pip install method (recommended)

!pip install ultralytics==8.0.196

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

# Commented out IPython magic to ensure Python compatibility.
!mkdir {HOME}/datasets
# %cd {HOME}/datasets

"""#INSTALLLING DATASET"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="lOKWzf4eLM24UqnreIUL")
project = rf.workspace("fyp-js1xw").project("fyp_data")
dataset = project.version(1).download("yolov8")

"""#CUSTOM TRAINING"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=25 plots=True

"""#Checking"""

!ls {HOME}/runs/detect/train/

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/confusion_matrix.png', width=600)

"""

```
# This is formatted as code
```

#VALIDATION"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=val model={HOME}/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml



"""## Inferring"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=predict model={HOME}/runs/detect/train/weights/best.pt conf=0.50 source="/content/drive/MyDrive/FYP/YOLOV8_M1/datasets/FLT Movement Vid 4.mp4" save=True

!yolo mode=val model={HOME}/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml split=test